<!DOCTYPE html>
<html>
<head>
    <META http-equiv="content-type" content="text/html; charset=windows-1251">
    <link rel="stylesheet" type="text/css" href="/style/base.css">
    <link rel="stylesheet" type="text/css" href="/style/admin.css">
    <link rel="stylesheet" type="text/css" href="/style/cart.css">
    <link rel="stylesheet" type="text/css" href="/style/checkout.css">
    <link rel="stylesheet" type="text/css" href="/style/product.css">
    <link rel="stylesheet" type="text/css" href="/style/store.css">
    <link rel="stylesheet" type="text/css" href="/style/bootstrap.min.css">
    <script type="text/javascript" src="/javascript/jquery.min.js"></script>
    <script type="text/javascript" src="/javascript/bootstrap.min.js"></script>
    <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
    <title>Student Webstore</title>
</head>
<div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="collapse navbar-collapse">
            <?php if(!isset($_SESSION)): ?>
                <?php session_start(); ?>
            <?php endif; ?>

            <?php if(!isset($_SESSION["userId"]) && !isset($_SESSION["adminId"])): ?>
                <ul class="login nav navbar-nav navbar-right btn-side">
                    <li><a href="?page=quote_list">curt</a></li>
                    <li><a href="?page=customer_login">Login</a></li>
                    <li><a href="?page=customer_register">Sign Up</a></li>
                </ul>
                <h3 class="navbar-header">Hello, please log in! </h3>
            <?php else: ?>
                <?php if(isset($_SESSION["adminId"])): ?>
                    <ul class="login nav navbar-nav navbar-right btn-side">
                        <li><a href="?page=admin_orders">Orders</a></li>
                        <li><a href="?page=admin_logout">Logout</a></li>
                    </ul>
                    <?php else: ?>
                    <ul class="login nav navbar-nav navbar-right btn-side">
                        <li><a href="?page=quote_list">Curt</a></li>
                        <li><a href="?page=customer_logout">Logout</a></li>
                    </ul>
                    <?php endif; ?>

                <h3 class="navbar-header">Good!!! Hello <?php echo($_SESSION["userName"]) ?> </h3>

            <?php endif; ?>

        </div>
    </div>
</div>
<body>
    <div class="page-content">
        <?php $this->renderTemplate() ?>
    </div>
</body>
</html>