<!DOCTYPE html>
<html ng-app="shopApp">
<head>
    <META http-equiv="content-type" content="text/html; charset=utf-8">
    <link rel="stylesheet" type="text/css" href="/style/base.css">
    <link rel="stylesheet" type="text/css" href="/style/admin.css">
    <link rel="stylesheet" type="text/css" href="/style/cart.css">
    <link rel="stylesheet" type="text/css" href="/style/checkout.css">
    <link rel="stylesheet" type="text/css" href="/style/product.css">
    <link rel="stylesheet" type="text/css" href="/style/store.css">
    <link rel="stylesheet" type="text/css" href="/style/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/style/font-awesome/css/font-awesome.min.css">
    <script type="text/javascript" src="/javascript/jquery.min.js"></script>
    <script type="text/javascript" src="/javascript/bootstrap.min.js"></script>
    <script type="text/javascript" src="/javascript/angular.min.js"></script>
    <script type="text/javascript" src="/javascript/controller/mainController.js"></script>
    <script type="text/javascript" src="/javascript/controller/productListController.js"></script>
    <script type="text/javascript" src="/javascript/controller/headerController.js"></script>
    <script type="text/javascript" src="/javascript/controller/viewProductController.js"></script>
    <script type="text/javascript" src="/javascript/controller/orderAdminController.js"></script>
    <script type="text/javascript" src="/javascript/filters/mainFilter.js"></script>
    <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
    <title>Student Webstore</title>
</head>
<div ng-controller="headerController" class="navbar navbar-default navbar-fixed-top opacity_header">
    <div class="container">
        <div class="collapse navbar-collapse">
            <?php if(!isset($_SESSION)): ?>
                <?php session_start(); ?>
            <?php endif; ?>
            <div class="nav navbar-nav navbar-left btn-side">
                <a href="/"><img class="logo" src="/images/shop-icon.png" alt=""/></a>
            </div>

            <?php if(!isset($_SESSION["userId"]) && !isset($_SESSION["adminId"])): ?>
                <ul class="login nav navbar-nav navbar-right btn-side">
                    <li><a href="?page=quote_list"><i class="fa fa-shopping-cart fa-3x cart_icon"></i></a></li>
                    <li><a href="?page=customer_login"><i class="fa fa-dot-circle-o fa-3x login_icon"></i></a></li>
                    <li><a href="?page=admin_login"><i class="fa fa-suitcase fa-3x"></i></a></li>
                    <li><a href="?page=customer_register"><i class="fa fa-sign-in fa-3x sign_up"></i></a></li>
                </ul>
                <h3 class="navbar-header">Пожалуйста зарегистрируйтесь! </h3>
            <?php else: ?>
                <?php if(isset($_SESSION["adminId"])): ?>
                    <ul class="login nav navbar-nav navbar-right btn-side">
                        <li><a href="?page=store_list"><i class="fa fa-cube fa-3x"></i></a></li>
                        <li><a href="?page=admin_orders"><i class="fa fa-cogs fa-3x"></i></a></li>
                        <li><a href="?page=admin_logout"><i class="fa fa-dot-circle-o fa-3x logout_icon"></i></a></li>
                    </ul>
                    <?php else: ?>
                    <ul class="login nav navbar-nav navbar-right btn-side">
                        <li><a href="?page=quote_list"><i class="fa fa-shopping-cart fa-3x cart_icon"></i></a></li>
                        <li><a href="?page=customer_logout"><i class="fa fa-dot-circle-o fa-3x logout_icon"></i></a></li>
                    </ul>
                    <?php endif; ?>

                <h3 class="navbar-header">Добро пожаловать <?php echo($_SESSION["userName"]) ?>! </h3>

            <?php endif; ?>

        </div>
    </div>
</div>
<body ng-controller="mainController">
    <div class="page-content">
        <?php $this->renderTemplate() ?>
    </div>
</body>
</html>