<script type="text/javascript" src="/javascript/geomap.js"></script>

<div class="orders center-block" >
    <h3 class="center-block page-header alert-success">
        Редактирование заказа!
    </h3>
    <div class="row">
        <table class="table table-condensed table-hover margin_padding_none">
        <?php $order = $this->get('orders') ?>
        <?php $storeCity = $this->get('storeCity') ?>

            <tr>
                <form name="Email Header" method="post" action="?page=admin_orders">
                    <th class="warning">Номер заказа</th>
                    <th class="warning">Статус</th>
                    <th class="warning">Дата</th>
                    <th class="warning">Город</th>
                    <th class="warning">Регион</th>
                    <th class="warning">Почтовый индекс</th>
                    <th class="warning">Улица</th>
                    <th class="warning">Дом</th>
                    <th class="warning">Квартира</th>
                    <th class="warning">Контактный телефон</th>
                </form>
            </tr>
            <tr>
                <td class="warning"><?php echo $order->getNumber(); ?></td>
                <td class="warning"><?php echo $order->getStatus() == 'Pending' ? "В ожидании" : "Утвержден"; ?></td>
                <td class="warning"><?php echo $order->getDate(); ?></td>
                <td class="warning"><?php echo $order->getCity(); ?></td>
                <td class="warning"><?php echo $order->getRegion(); ?></td>
                <td class="warning"><?php echo $order->getPostalCode(); ?></td>
                <td class="warning"><?php echo $order->getStreet(); ?></td>
                <td class="warning"><?php echo $order->getHomeNumber(); ?></td>
                <td class="warning"><?php echo $order->getFlat(); ?></td>
                <td class="warning"><?php echo $order->getPhone(); ?></td>

            </tr>
            </table>
        </div>
        <div class="row">

        <table class="table table-condensed table-hover margin_padding_none">

            <tr>
                <form name="Email Header" method="post" action="?page=admin_orders">
                    <th class="success">Покупатель</th>
                    <th class="success">Способ доставки</th>
                    <th class="success">Способ оплаты</th>
                    <th class="success">Общий итог</th>
                    <th class="success">Дистанция</th>
                    <th class="success">Приблизительное время</th>
                </form>
            </tr>
            <tr>
                <td class="success"><?php if($order->getCustomer() == null) echo "Гость"; else echo $order->getCustomer();?></td>
                <td class="success"><?php if($order->getShippingMethod() == "Table rate") { echo "по стоимости в регионе"; } else if ($order->getShippingMethod() == "fixed") { echo "Фиксированная"; }?></td>
                <td class="success"><?php echo $order->getPaymentMethod() == 'Cash on delivery' ? 'Наложенный платеж' : ''; ?></td>
                <td class="success"><?php echo $order->getGrandTotal(); ?></td>
                <td class="success"><?php echo $order->getDistance(); ?></td>
                <td class="success"><?php echo $order->getDuration(); ?></td>
                <td class="success"><?php echo $storeCity->getName(); ?></td>
            </tr>
            </table>
        </div>
        <div class="row">
            <table class="table table-condensed table-hover margin_padding_none">

                <tr>
                    <th class="danger">Название товара</th>
                    <th class="danger">Идентификатор</th>
                    <th class="danger">Количество</th>
                    <th class="danger">Цена</th>
                </tr>
                <?php foreach ($this->get('OPCollection') as $itemProduct): ?>
                <tr>
                    <td class="danger"><?php echo $itemProduct->getProductName(); ?></td>
                    <td class="danger"><?php echo $itemProduct->getProductSku(); ?></td>
                    <td class="danger"><?php echo $itemProduct->getProductQty(); ?></td>
                    <td class="danger"><?php echo $itemProduct->getProductPrice(); ?></td>
                </tr>
                <?php endforeach; ?>
            </table>
        </div>
    <div class="row">
        <form name="Email Header" method="post" action="?page=admin_editOrder&id=<?php echo $order->getId()?>">
            <input type="submit" class="btn btn-default width_full" name="approve" value="Утвердить">
        </form>
    </div>
    <input type="text" id="cityAddressCustomer" value="<?php echo $order->getCity(); ?>" hidden=""/>
    <input type="text" id="cityAddressStore" value="<?php echo $storeCity->getName() ?>" hidden=""/>


<!--    <input type="text" class="btn btn-default width_full" value="Показать карту" ng-click="isMap = !isMap">-->
    <div style="width:800px; height: 350px;" >
    <div id="map_canvas" style="width:800px; height: 350px;"></div>

    <div id="outputDiv"></div>
    </div>
