<div class="orders center-block" >
    <h3 class="center-block page-header alert-success">
        Edit order!
    </h3>
    <div class="row">
        <table class="table table-condensed table-hover margin_padding_none">
        <?php $order = $this->get('orders') ?>
            <tr>
                <form name="Email Header" method="post" action="?page=admin_orders">
                    <th class="warning">Number order</th>
                    <th class="warning">Status</th>
                    <th class="warning">Date</th>
                    <th class="warning">City</th>
                    <th class="warning">Region</th>
                    <th class="warning">Postal Code</th>
                    <th class="warning">Street</th>
                    <th class="warning">Flat</th>
                </form>
            </tr>
            <tr>
                <td class="warning"><?php echo $order->getNumber(); ?></td>
                <td class="warning"><?php echo $order->getStatus(); ?></td>
                <td class="warning"><?php echo $order->getDate(); ?></td>
                <td class="warning"><?php echo $order->getCity(); ?></td>
                <td class="warning"><?php echo $order->getRegion(); ?></td>
                <td class="warning"><?php echo $order->getPostalCode(); ?></td>
                <td class="warning"><?php echo $order->getStreet(); ?></td>
                <td class="warning"><?php echo $order->getFlat(); ?></td>

            </tr>
            </table>
        </div>
        <div class="row">

        <table class="table table-condensed table-hover margin_padding_none">

            <tr>
                <form name="Email Header" method="post" action="?page=admin_orders">
                    <th class="success">Customer name</th>
                    <th class="success">Shipping Method</th>
                    <th class="success">Payment Method</th>
                    <th class="success">Grand total</th>
                    <th class="success">Distance</th>
                    <th class="success">Duration</th>
                </form>
            </tr>
            <tr>
                <td class="success"><?php echo $order->getCustomer(); ?></td>
                <td class="success"><?php echo $order->getShippingMethod(); ?></td>
                <td class="success"><?php echo $order->getPaymentMethod(); ?></td>
                <td class="success"><?php echo $order->getGrandTotal(); ?></td>
                <td class="success"><?php echo $order->getDistance(); ?></td>
                <td class="success"><?php echo $order->getDuration(); ?></td>
            </tr>
            </table>
        </div>
        <div class="row">
            <table class="table table-condensed table-hover margin_padding_none">

                <tr>
                    <th class="danger">Name Product</th>
                    <th class="danger">Sku</th>
                    <th class="danger">Count</th>
                    <th class="danger">Price</th>
                </tr>
                <?php foreach ($this->get('OPCollection') as $itemProduct): ?>
                <tr>
                    <td class="danger"><?php echo $itemProduct->getProductName(); ?></td>
                    <td class="danger"><?php echo $itemProduct->getProductSku(); ?></td>
                    <td class="danger"><?php echo $itemProduct->getProductQty(); ?></td>
                    <td class="danger"><?php echo $itemProduct->getProductPrice(); ?></td>
                </tr>
                <?php endforeach; ?>
            </table>
        </div>
    <div class="row">
        <form name="Email Header" method="post" action="?page=admin_editOrder&id=<?php echo $order->getId()?>">
            <input type="submit" class="btn btn-default width_full" name="approve" value="Approve">
        </form>

</div>
