<div class="orders center-block" ng-controller="orderAdminController" >
    <h3 class="center-block page-header alert-success">
        Orders!
    </h3>
    <br>

    <div class=" center-block tableOrders">
        <?php foreach($this->get('orders') as $order): ?>
            <div ng-show="false" class="hidden" ng-init="loadOrders('<?php echo $order['number_order'] ?>',
                                                       '<?php echo $order['created_at'] ?>',
                                                        '<?php echo $order['grand_total'] ?>',
                                                        '<?php echo $order['status'] ?>',
                                                        '<?php echo $order['order_id'] ?>'
            )" ></div>
        <?php endforeach; ?>
        <div class="row">
            <div class="control-group">
                <input class="form-control" type="text" placeholder="filter" ng-model="filterOrder" ng-keypress="enterFilterOrder(filteredItems)"/>
            </div>
        </div>
        <div class="row">
            <table class="table table-condensed table-hover margin_padding_none">
                <tr>
                    <form name="Email Header" method="post" action="?page=admin_orders">
                        <th class="active padding_none"><button type="submit" name="sort[number_order]" class="btn btn-default th-btn "  value="<?php echo 1-$this->get('id_sort') ?>">Number order</button></th>
                        <th class="success padding_none"><button type="submit" name="sort[created_at]" class="btn btn-success th-btn " value="<?php echo 1-$this->get('id_sort') ?>">Date</button></th>
                        <th class="warning padding_none"><button type="submit" name="sort[grand_total]"  class="btn btn-warning th-btn " value="<?php echo 1-$this->get('id_sort') ?>">Grand total</button></th>
                        <th class="danger padding_none"><button type="submit" name="sort[status]" class="btn btn-danger th-btn " value="<?php echo 1 - $this->get('id_sort') ?>">Status</button></th>
                        <th class="danger padding_none"></th>
                    </form>
                </tr>

                <tr>
                    <th class="active">Number order</th>
                    <th class="success">Date</th>
                    <th class="warning">Grand total</th>
                    <th class="danger">Status</th>
                    <th class="danger"></th>
                </tr>

                <tr ng-repeat="order in (filteredItems = (allOrders | filter: filterOrder) | startFrom:currentPage*pageSize | limitTo:pageSize )">
                    <td class="active">{{ order.number }}</td>
                    <td class="success">{{ order.date }}</td>
                    <td class="warning">{{ order.grandTotal }}</td>
                    <td class="danger">{{ order.status }}</td>
                    <td class="danger"><a href="?page=admin_editOrder&id={{ order.id }}"><i class="fa fa-pencil-square-o"></i></a></td>
                </tr>
            </table>
        </div>
        <div class="row" ng-init="editPage(1)">
            <div ng-if="pages > 1" class=" btn-group" ng-repeat="page in [] | range:pages">
                <div class="btn btn-default" ng-class="{'active': currentPage-1 === $index }" ng-click="editPage(page+1)" >{{ page + 1  }}</div>
            </div>
        </div>
    </div>

</div>
<!--        <div>-->
<!--            <form action="?page=admin_orders" method="POST">-->
<!--                <select name="filter[key]">-->
<!--                    <option value="number_order">Number order</option>-->
<!--                    <option value="created_at">Date</option>-->
<!--                    <option value="grand_total">Grand total</option>-->
<!--                    <option value="status">Status</option>-->
<!--                </select>-->
<!--                <input type="search" name="filter[value]" placeholder="input filter" >-->
<!--                <input type="submit" value="Filter" >-->
<!--            </form>-->
<!--        </div>-->