<div class="login_register" >
    <h3 class="center-block login_form alert-info padding_add_20px">
        Авторизация Администрация!
    </h3>
    <form class="center-block login_form alert-success" action="?page=admin_login" method="POST">
        <div class="padding_add_20px">
            <div class="form-group">
                <label for="name">Логин</label>
                <input class="center-block form-control" type="text" id="name" name="admin[name]" />
            </div>
            <div class="form-group">
                <label for="password">Пароль</label>
                <input class="center-block form-control" type="password" id="password" name="admin[password]" />
            </div>

            <input class="btn btn-default"  type="submit" value="Вход">
        </div>
    </form>
</div>
