<!--<script type="text/javascript" src="/javascript/geomap.js"></script>-->
<h3 class="center-block login_form page-header alert-success padding_add_20px">
    Заказ!
</h3>
<form class="center-block login_form font_20 padding_add_20px alert-info" action="/?page=checkout_order" method="post">

    <div class="form-group">
        <label class="form-control">
            Цена за выбранные товары: <?php echo $this->get('subtotal') ?>$
        </label>
    </div>

    <div class="form-group">
        <label class="form-control">
            Цена за доставку: <?php echo $this->get('shipping') ?>$
        </label>
    </div>

    <div class="form-group">
        <label class="form-control">
            Итоговая цена: <?php echo $this->get('grand_total') ?>$
        </label>
    </div>


    <div><input class="btn btn-success" type="submit" value="Все верно. Оформить заказ!"></div>
</form>
<!--<div id="map_canvas" style="width:500px; height: 500px;"></div>-->
<!--<div id="outputDiv"></div>-->
