<h3 class="center-block login_form page-header alert-success padding_add_20px">
    Payment!
</h3>
<form class="center-block width_checkout--bnt--50 font_20 padding_add_20px alert-warning" action="/?page=checkout_payment" method="post">


    <?php foreach($this->get('methods') as $method): ?>
        <div  class="radio">
            <label>
                <input type="radio" name="method" value="<?php echo $method->getCode() ?>">
                <?php echo $method->getLabel() ?>
            </label>
        </div>
    <?php endforeach; ?>

    <div><input type="submit" value="Finish"></div>
</form>