<div class="row">
    <h3 class="center-block login_form page-header alert-success padding_add_20px">
        Введите адрес доставки!
    </h3>
    <form class="center-block login_form padding_add_20px alert-warning" action="?page=checkout_address" method="POST">
        <div class="form-group">
            <select class="center-block form-control" name="address[city_id]" id="city">
                <?php foreach($this->get('cities') as $_city): ?>
                    <option value="<?php echo $_city->getId(); ?>"><?php echo $_city->getName(); ?></option>
                <?php endforeach; ?>
            </select>
        </div>

        <div class="form-group">
            <select class="center-block form-control" name="address[region_id]" id="region">
                <?php foreach($this->get('regions') as $_region): ?>
                    <option value="<?php echo $_region->getId(); ?>"><?php echo $_region->getName(); ?></option>
                <?php endforeach; ?>
            </select>
        </div>

        <div class="form-group">
            <input class="center-block form-control" placeholder="Почтовый индекс" type="text" name="address[postal_code]">
        </div>

        <div class="form-group">
            <input class="center-block form-control" placeholder="Улица" type="text" name="address[street]">
        </div>

        <div class="form-group">
            <input class="center-block form-control" placeholder="Номер дома" type="text" name="address[home_number]">
        </div>

        <div class="form-group">
            <input class="center-block form-control" placeholder="Квартира" type="text" name="address[flat]">
        </div>
        <div class="form-group">
            <input class="center-block form-control" placeholder="Телефон" type="text" name="address[phone]">
        </div>
        <input class="btn btn-success" type="submit" value="Далее"/>
    </form>
</div>