<div class="login_register">

    <h3 class="center-block login_form alert-info padding_add_20px">
        Register!
    </h3>

    <form class="center-block login_form alert-danger" action="?page=customer_register" method="POST">
        <div class="padding_add_20px">
            <div class="form-group">
                <label for="name">Name</label>
                <input class="center-block form-control" type="text" id="name" name="customer[name]" />
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input class="center-block form-control" type="text" id="password" name="customer[password]" />
            </div>

            <input class="btn btn-default"  type="submit" value="Register">
        </div>
    </form>
</div>