<div class="products product_view">
    <div class="row">
        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
            <img src="<?php echo $this->get('product')->getImage();?>" />
        </div>
        <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
            <label>Name: </label>
            <h3><?php echo $this->get('product')->getName() ?></h3>
        </div>
    </div>

    <div>

        <span>Sku: </span>
        <span><?php echo $this->get('product')->getSku() ?></span>
        <br>
        <span>Price: </span>
        <span><?php echo $this->get('product')->getPrice() ?></span>
        <br>
        <?php if ($this->get('product')->isSpecialPriceApplied()): ?>
            <span class="special">Special Price: </span>
            <span class="special"><?php echo $this->get('product')->getSpecialPrice()  ?></span>
        <?php endif; ?>
    </div>
</div>
<label for="count">Available quantity - <?php echo $this->get('product')->getQty() ?>: </label>

<form action="?page=quote_add" method="POST">
    <input type="text" name="quote[product_id]" value="<?php echo $this->get('product')->getId();?>" hidden>
    <input type="submit" id = "<?php echo $this->get('product')->getId();?>" value="Add quote" />
</form>


<?php if(isset($_SESSION["userId"]) || isset($_SESSION["adminId"])): ?>
    <form action="?page=product_addReview" method="POST">
        <div>
            <label>Name: </label>
            <input type="text" name="review[name]">
        </div>

        <div>
            <label>Email: </label>
            <input type="text" name="review[email]">
        </div>

        <div>
            <label>Text: </label>
            <textarea rows="10" cols="45" name="review[text]"></textarea>
        </div>

        <div>
            <label>Rating: </label>
            <input type="text" name="review[rating]">
        </div>

        <input type="text" name="review[product_id]" value="<?php echo $this->get('product')->getId() ?>" hidden>
        <input type="text" name="review[customer_id]" value="<?php echo $_SESSION["userId"] ?>" hidden>

        <input type="submit" value="Add review"/>
    </form>
 <?php endif; ?>

<div class="reviews">
    <h2>Reviews!</h2>

<!--    <h3 id = 'valueRating'>--><?php //echo $reviewsAll->getAverageRating(); ?><!--</h3>-->
    <?php for ($page = 1; $page <= $this->get('pages')->pageCount; $page++): ?>
        <a href="/?page=product_view&id=<?php echo $this->get('product')->getId();?>&p=<?php echo $page; ?>"><?php echo $page; ?></a>
    <?php endfor; ?>
    <br>

    <?php foreach ($this->get('reviews') as $_review): ?>

        <div class="review">
            <span>Product_id: </span>
            <h2 id = 'productID'><?php echo $this->get('product')->getId() ?></h2>
            <lable>Name: </lable>
            <h4><?php echo $_review->getName() ?></h4>
            <lable>E-mail: </lable>
            <div class="value"><?php echo $_review->getEmail() ?></div>
            <lable>Description: </lable>
            <div class="value"><?php echo $_review->getText() ?></div>
            <lable>Rating: </lable>
            <div class="value"><?php echo $_review->getRating() ?></div>
        </div>
        <br>
        <a href="?page=product_deleteReview&review_id=<?php echo $_review->getId();?>&id=<?php echo $this->get('product')->getId();?>">Delete <?php echo $this->get('product')->getName(); ?></a>

    <?php endforeach; ?>
</div>
