<div class="row">
   <?php foreach ($this->get('stores') as $key => $_store): ?>

    <a href="?page=store_view&id=<?php echo $_store->getId(); ?>">
        <div class="products stores">
            <div>
                <label>Название склада: </label>
                <h2><?php echo $_store->getName() ?></h2>
                <br>
                <label>Идентификатор адреса: </label>
                <span><?php echo $_store->getAddressId() ?></span>
<!--                <label>City name: </label>-->
<!--                <span>--><?php //echo $this->get('cityList')[$key] ?><!--</span>-->
<!--                <label>Postal Code: </label>-->
<!--                <span>--><?php //echo $this->get('addressList')[$key]['postal'] ?><!--</span>-->
<!--                <label>Street: </label>-->
<!--                <span>--><?php //echo $this->get('addressList')[$key]['street'] ?><!--</span>-->
<!--                <label>Home Number: </label>-->
<!--                <span>--><?php //echo $this->get('addressList')[$key]['homeNumber'] ?><!--</span>-->
<!--                <label>Flat: </label>-->
<!--                <span>--><?php //echo $this->get('addressList')[$key]['flat'] ?><!--</span>-->

                <br>
            </div>
        </div>
    </a>
    <a href="?page=store_edit&store_id=<?php echo $_store->getId(); ?>">Обновить <?php echo $_store->getName(); ?></a>

    <br>

    <?php endforeach; ?>
</div>

<div class="row">
<form class="add_product add_store" action="?page=store_add" method="POST">
    <div class="form-group">
        <input class="form-control" type="text" name="store[name]" placeholder="Название склада">
    </div>

    <div class="form-group">
        <select class="form-control"  class="form-control" name="address[city_id]" id="city">
            <option selected value="">Выберите город</option>
            <?php foreach($this->get('city') as $_city): ?>
                <option value="<?php echo $_city->getId(); ?>"><?php echo $_city->getName(); ?></option>
            <?php endforeach; ?>
        </select>
    </div>

    <div class="form-group">
        <select class="form-control" name="address[region_id]" id="region">
            <option selected value="">Выберите регион</option>
            <?php foreach($this->get('region') as $_region): ?>
                <option value="<?php echo $_region->getId(); ?>"><?php echo $_region->getName(); ?></option>
            <?php endforeach; ?>
        </select>
    </div>

    <div class="form-group">
        <input class="form-control" type="text" name="address[postal_code]" placeholder="Почтовый индекс">
    </div>

    <div class="form-group">
        <input class="form-control" type="text" name="address[street]" placeholder="Улица">
    </div>

    <div class="form-group">
        <input class="form-control" type="text" name="address[home_number]" placeholder="Номе бокса">
    </div>

    <div class="form-group">
        <input class="form-control" type="text" name="address[flat]" placeholder="Номер отдела">
    </div>

    <input class="btn btn-default" type="submit" value="Добавить склад"/>
</form>
</div>

<div class="row">

<?php for ($page = 1; $page <= $this->get('pages')->pageCount; $page++): ?>
    <a href="?page=store_list&p=<?php echo $page; ?>"><?php echo $page; ?></a>
<?php endfor; ?>
<br>

</div>

