<div class="products">
    <div>
        <span>Наименование: </span>
        <h2><?php echo $this->get('store')->getName() ?></h2>
        <span>Идентификатор адреса: </span>
        <span><?php echo $this->get('store')->getAddressId() ?></span>
        <label>Город: </label>
        <span><?php echo $this->get('city')->getName() ?></span>
        <label>Почтовый индекс: </label>
        <span><?php echo $this->get('address')->getPostalCode() ?></span>
        <label>Улица: </label>
        <span><?php echo $this->get('address')->getStreet() ?></span>
        <label>Номер Бокса: </label>
        <span><?php echo $this->get('address')->getHomeNumber() ?></span>
        <label>Номер отдела: </label>
        <span><?php echo $this->get('address')->getFlat() ?></span>
        <br>
    </div>
</div>


<?php if(isset($_SESSION["userId"]) || isset($_SESSION["adminId"])): ?>
    <form action="?page=store_addProductStore" method="POST">
        <div>
            <label>Идентификатор: </label>
            <input type="text" name="productStore[sku]">
        </div>

        <div>
            <label>Количество: </label>
            <input type="text" name="productStore[qty]">
        </div>

        <input type="text" name="productStore[store_id]" value="<?php echo $this->get('store')->getId() ?>" hidden>

        <input type="submit" value="Добавит товар"/>
    </form>
 <?php endif; ?>

<div class="reviews">
    <h2>Товары на складе</h2>

    <!--    <h3 id = 'valueRating'>--><?php //echo $reviewsAll->getAverageRating(); ?><!--</h3>-->
    <?php for ($page = 1; $page <= $this->get('pages')->pageCount; $page++): ?>
        <a href="/?page=store_view&id=<?php echo $this->get('store')->getId();?>&p=<?php echo $page; ?>"><?php echo $page; ?></a>
    <?php endfor; ?>
    <br>

    <?php foreach ($this->get('productStores') as $_product): ?>
        <div class="review">
            <lable>Идентификатор склада: </lable>
            <h4><?php echo $_product->getStoreId() ?></h4>
            <lable>Идентификатор товара: </lable>
            <div class="value"><?php echo $_product->getSku() ?></div>
            <lable>Количество: </lable>
            <div class="value"><?php echo $_product->getQty() ?></div>
        </div>
        <br>
        <a href="?page=store_deleteProductStore&product_store_id=<?php echo $_product->getId();?>&id=<?php echo $this->get('store')->getId();?>">Удалить <?php echo $this->get('store')->getName(); ?></a>

    <?php endforeach; ?>
</div>
