<form action="?page=store_add" method="POST">
    <input type="text" name="store[store_id]" value="<?php echo($this->get('store')->getId()) ?>" hidden>
    <input type="text" name="store[address_id]" value="<?php echo($this->get('address')->getId()) ?>" hidden>
    <input type="text" name="address[address_id]" value="<?php echo($this->get('address')->getId()) ?>" hidden>

    <div>
        <label>Название склада: </label>
        <input type="text" name="store[name]" value="<?php echo($this->get('store')->getName()) ?>">
    </div>

    <div class="address_input">
        <label for="city">Город: </label>
        <select name="address[city_id]" id="city">
            <?php foreach($this->get('cities') as $_city): ?>
                <option value="<?php echo $_city->getId(); ?>"><?php echo $_city->getName(); ?></option>
            <?php endforeach; ?>
        </select>
    </div>

    <div class="address_input">
        <label for="region">Регион: </label>
        <select name="address[region_id]" id="region">
            <?php foreach($this->get('regions') as $_region): ?>
                <option value="<?php echo $_region->getId(); ?>"><?php echo $_region->getName(); ?></option>
            <?php endforeach; ?>
        </select>
    </div>

    <div class="address_input">
        <label for="postal_code">Почтовый индекс: </label>
        <input type="text" name="address[postal_code]" value="<?php echo($this->get('address')->getPostalCode()) ?>">
    </div>

    <div class="address_input">
        <label for="street">Улица: </label>
        <input type="text" name="address[street]" value="<?php echo($this->get('address')->getStreet()) ?>">
    </div>

    <div class="address_input">
        <label for="home_number">Номер бокса: </label>
        <input type="text" name="address[home_number]" value="<?php echo($this->get('address')->getHomeNumber()) ?>">
    </div>

    <div class="address_input">
        <label for="flat">Номер отдела: </label>
        <input type="text" name="address[flat]" value="<?php echo($this->get('address')->getFlat()) ?>">
    </div>

    <input type="submit" value="Обновить"/>
</form>
<a href="?page=store_delete&store_id=<?php echo $this->get('store')->getId(); ?>">Удалить <?php echo $this->get('store')->getName(); ?></a>

